FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SB_PUBLISHABLE_KEY
ARG VITE_IS_DEMO=false
ARG VITE_INBOUND_EMAIL=
ARG VITE_ATTACHMENTS_BUCKET=attachments
ARG VITE_GOOGLE_WORKPLACE_DOMAIN=
ARG VITE_DISABLE_EMAIL_PASSWORD_AUTHENTICATION=false

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SB_PUBLISHABLE_KEY=$VITE_SB_PUBLISHABLE_KEY
ENV VITE_IS_DEMO=$VITE_IS_DEMO
ENV VITE_INBOUND_EMAIL=$VITE_INBOUND_EMAIL
ENV VITE_ATTACHMENTS_BUCKET=$VITE_ATTACHMENTS_BUCKET
ENV VITE_GOOGLE_WORKPLACE_DOMAIN=$VITE_GOOGLE_WORKPLACE_DOMAIN
ENV VITE_DISABLE_EMAIL_PASSWORD_AUTHENTICATION=$VITE_DISABLE_EMAIL_PASSWORD_AUTHENTICATION

RUN npm run build

FROM nginx:1.27-alpine

COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -qO- http://127.0.0.1/ >/dev/null || exit 1
